version: '3.8'

services:
  python:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./:/var/www/
      - python_vol:/usr/local/bin/
    ports:
      - "8000:8000"
    networks:
      - backend

  postgres:
    build:
      context: ./
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend

volumes:
  postgres:
    driver: local
  python_vol:
    driver: local

networks:
  backend: