# Generated by Django 4.2.11 on 2025-02-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='category_id',
        ),
    ]
