# Generated by Django 4.2.11 on 2025-02-18 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('blogs', '0002_blogcategory_blog_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='blogcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='blogcategory',
            unique_together={('blog', 'category')},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='blogcategory',
            table='blog_category',
        ),
    ]
