# Generated by Django 4.2.11 on 2025-02-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_category_blog_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category_id',
            new_name='category',
        ),
    ]
